#
###################################
# Site wide configuration
####################################
#
title: "Ronnie's Ramblings"
email: ronniemhowell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog.  Updated rarely, intellegable even less so
url: #http://rhowell.github.io

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter: pygments
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Jekyll configuration
####################################
#
owner:
  name: Ronnie Howell
  avatar: bio-photo.jpg
  bio: >
    Dad, husband, software engineer.<br>
    Frozen in upstate New York: please send coffee
  email: ronniemhowell@gmail.com
  disqus-shortname: 
  twitter: ronniemhowell #username
  facebook: ronniemhowell #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rhowell #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
